### ISSUE TITLE
Themed Icon (Android 13)

### ISSUE THREAD

**Issue by thgoebel** [tom-anders/Easy-xkcd#321]
Please consider adding support for Themed Icons in Android 13.
See https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#add_your_adaptive_icon_to_your_app

Search keywords: Themed Icons, Material You, monochrome, app icon.

**Comment by tom-anders** [comment]
Cool, thanks! Will try to have a look at it tomorrow and create a new release.
